### ISSUE TITLE
unable to read config invalid character '"' after object key:value pair

### ISSUE THREAD

**Issue by MexTrx** [TimIsOverpowered/twitch-recorder-go#1]
When attempting to run I get an error that _"unable to read config invalid character '"' after object key:value pair"_

{
    "twitch": {
        "client_id": "myclientID",
        "client_secret": "mykey"
        "oauth_key": ""
    },
    "vod_directory": "C:\Users\admin\twitch-recorder-go-main\recordings",
    "channels": [
        "shroud", 
        "KristoferYee",
    ],
    "twitch_app": {
        
    },
    "drive": {
        "refresh_token": "",
        "access_token": ""
    },
    "google": {
        "client_id": "",
        "client_secret": "",
        "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
        ],
    "endpoint": {
        "token_url": "https://oauth2.googleapis.com/token"
    }

}

**Comment by TimIsOverpowered** [comment]
The JSON syntax is not correct. That is why it is failing.

You can copy the one from the [README ](https://github.com/TimIsOverpowered/twitch-recorder-go/blob/main/README.md) and just directly change the values you need so it will be valid.
